# development:
#   :address: smtp.gmail.com
#   :port: 587
#   :authentication: plain
#   :user_name: wadhwa.saurabh@gmail.com
#   :password: ragedeath111
#   :enable_starttls_auto: true

# staging:
#   :address: smtp.gmail.com
#   :port: 587
#   :authentication: plain
#   :user_name: wadhwa.saurabh@gmail.com
#   :password: ragedeath111
#   :enable_starttls_auto: true
# production:
#   :address: smtp.gmail.com
#   :port: 587
#   :authentication: plain
#   :user_name: wadhwa.saurabh@gmail.com
#   :password: ragedeath111
#   :enable_starttls_auto: true
